spring.application.name=parking-lot
# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_lot
spring.datasource.username=parking_lot
spring.datasource.password=parking_lot
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
# ===============================
# SQL LOG
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# logging.level.org.hibernate.orm.jdbc.bind=TRACE
